### ISSUE TITLE
The National Archives/Discovery API

### ISSUE THREAD

**Issue by mentionthewar** [alphagov/api-catalogue#103]
**Base URL:**
https://discovery.nationalarchives.gov.uk/API

**Name:**
Discovery

**Description:**
Our Discovery application programming interface (API) is designed to maximise access to the information held in The National Archives' Discovery service. Discovery holds more than 35 million descriptions of records held by The National Archives and more than 2,500 archives and institutions across the United Kingdom, as well as a smaller number of archives around the world. The information in Discovery is made up of record descriptions provided by or derived from the catalogues of the different archives. Discovery also contains significant information on hundreds of thousands of record creators from anonymous diarists to the world renowned.

The API is open and a sandbox and documentation are provided.

**Documentation URL:**
https://discovery.nationalarchives.gov.uk/API/sandbox/index#!/
http://www.nationalarchives.gov.uk/help/discovery-for-developers-about-the-application-programming-interface-api/

**Maintainer:**
discovery@nationalarchives.gov.uk

**Provider:**
The National Archives

**Provider URL:**
https://www.nationalarchives.gov.uk/

**Comment by charlesbaird-dsa** [comment]
Hi @mentionthewar - thanks for including the TNA Discovery API in the Catalogue - as you can see that's now been published. Would you be able to point me in the direction of who to talk to about getting the other TNA APIs on there, please? Feel free to drop me a line at charles.baird@digital.cabinet-office.gov.uk
