### ISSUE TITLE
Clicking on "API Catalogue" in the top left takes you to another website

### ISSUE THREAD

**Issue by MatMoore** [alphagov/api-catalogue#14]
I clicked on "API catalogue" expecting to be taken to the home page of this microsite. Instead it took me to https://alphagov.github.io/, which is not aimed at government teams and doesn't mention the API catalogue.

Should this be changed?

**Comment by alex-ju** [comment]
Thank for raising this @MatMoore! It seems like this is a problem with the [tech-docs-template](https://github.com/alphagov/tech-docs-template) which doesn't render [the link provided in config](https://github.com/alphagov/api-catalogue/blob/master/config/tech-docs.yml#L7). Will raise that there and try to investigate it.

**Comment by alex-ju** [comment]
An update on this, it was fixed in the [tech-docs-gem](https://github.com/alphagov/tech-docs-gem/pull/119) but it's waiting for a new release.

**Comment by sihugh** [comment]
This appears to be fixed now, assuming I understood the initial problem. Can you confirm @MatMoore ?

**Comment by MatMoore** [comment]
Yep 👍
