### ISSUE TITLE
Add DEFRA Air Quality Sensor Observation Service

### ISSUE THREAD

**Issue by ghobona** [alphagov/api-catalogue#154]
**Please fill in the following information:**

**Base URL:**

https://uk-air.defra.gov.uk/sos-ukair/service?service=SOS&request=GetCapabilities

**Name:**
UK-AIR Sensor Observation Service

**Description:**

This is an [OGC](https://www.ogc.org) standards based Sensor Observation Service interface to Defra's UK Air Information Resource (UK-AIR). The service supports the UK obligations to European air quality e-Reporting initiative & Defra Open Data policy. The SOS provides a machine readable access point for air pollution measurements funded by Defra, Scottish Government, Welsh Government & Department of the Environment Northern Ireland. The service implements [INSPIRE guidelines](https://inspire.ec.europa.eu/id/document/tg/download-sos). For more on the European air quality e-Reporting initiative go to http://www.eionet.europa.eu/aqportal.. The OGC SOS 2.0 standard is described at https://www.ogc.org/standards/sos

**Documentation URL:**

https://uk-air.defra.gov.uk/data/about_sos

**Maintainer:**

The service provider is described on the Capabilities document as: Ricardo Energy & Environment (http://ee.ricardo.com/cms/). The phone number and email address are on the GetCapabilities response document in the `<ows:ServiceProvider>` element.

**Provider:**

Department for Environment, Food and Rural Affairs (https://uk-air.defra.gov.uk)

**Area Served:**
Optional - The geographic area that the API serves. For example: 'Greater London'.

**Start Date:**
Optional - The date the API comes into service. For example: '2020-07-01'.

**End Date:**
Optional - The date the API will be retired. For example: '2022-07-01'.

**Alternate Name:**
Optional - the acronym of the department or organisation. For example: 'GDS'.

**Provider URL:**

https://uk-air.defra.gov.uk

**Comment by ghobona** [comment]
Cc: @airqualityanthony

**Comment by airqualityanthony** [comment]
Hey, thanks for tagging me @ghobona as it's interesting but was there a specific reason?

**Comment by ghobona** [comment]
Hi @airqualityanthony . It was simply to make you aware of the catalogue entry.
