### ISSUE TITLE
Insolvency Service: Debt Respite Scheme (Breathing Space)

### ISSUE THREAD

**Issue by ifothergill-ins** [alphagov/api-catalogue#157]
**Please fill in the following information:**

**Base URL:**
https://www.gov.uk/api/debt-respite-scheme

**Name:**
Debt Respite Scheme (Breathing Space)

**Description:**
The Debt Respite Scheme (Breathing Space) will give someone in problem debt the right to legal protections from their creditors.  This API allows Money Advisers to manage their clients through a breathing space, whilst also allowing Creditors to digitally interact with the service.

Further information can be found in the following links:
[Debt Respite Scheme (Breathing Space) - Guidance for Money Advisers](https://www.gov.uk/government/publications/debt-respite-scheme-breathing-space-guidance/debt-respite-scheme-breathing-space-guidance-for-money-advisers)
[Debt Respite Scheme (Breathing Space) - Guidance for Creditors](https://www.gov.uk/government/publications/debt-respite-scheme-breathing-space-guidance/debt-respite-scheme-breathing-space-guidance-for-creditors)

**Documentation URL:**
https://gitlab.com/breathing-space-scheme/breathing-space

**Maintainer:**
breathingspaceproject@insolvency.gov.uk

**Provider:**
Insolvency Service

**Area Served:**
England & Wales

**Start Date:**
May 4th 2021

**End Date:**
N/A

**Alternate Name:**

**Provider URL:**

**Comment by charlesbaird-dsa** [comment]
Added
