### ISSUE TITLE
Re: 'Food Hygiene Ratings Scheme (FHRS)'

### ISSUE THREAD

**Issue by slingboi** [alphagov/api-catalogue#164]
Problem with 'Food Hygiene Ratings Scheme (FHRS)' (https://www.api.gov.uk/fsa/food-hygiene-ratings-scheme-fhrs/)

Hi, I've tried to call the api (e.g. https://api.ratings.food.gov.uk/Regions) from an iOS device but I'm not getting any response, even with parameters included as specified. I may have misunderstood but at the moment for me it isn't working, so just wanted to clarify. Thanks

**Comment by slingboi** [comment]
Hi @arnau thanks for the reply. Do you have any way to contact FSA? As I don't see any contact info on the API website.

**Comment by arnau** [comment]
I'm afraid I don't at the moment. @charlesbaird-dsa can you take this one?

**Comment by slingboi** [comment]
Oh ok that's alright, thanks also

**Comment by tkounenis** [comment]
Same issue here. Any API calls return an error message similar to this one:

`<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">The API 'Regions' doesn't exist</string>`

**Comment by charlesbaird-dsa** [comment]
Hi - I'll pass this on to the FSA and try and get some advice for you.

**Comment by charlesbaird-dsa** [comment]
Hi - the relevant APIs have been updated with a contact email - data@food.gov.uk - get in touch with the team directly to discuss these issues.
