### ISSUE TITLE
Energy Performance Certificates - Domestic Buildings Search API

### ISSUE THREAD

**Issue by Jaime-CT** [alphagov/api-catalogue#229]
Good morning team,
 
At Santander bank, we are working on a new functionality that will allow our customers to see the EPC for their houses. In order to provide this functionality, we are planning to use the public apis from gov.uk.
 
These apis cover almost the 100% of the functionality requested by the product owner of the project. However, we are missing the following information:
 
Assessor’s name (company who originally generated the EPC)
Assessor’s details
Further description of proposed home improvements to make the house more efficient in terms of energy.
 
Are you planning to include the above information at any point in the future? Otherwise, do you know if this information is available in any public database, so we can maybe access to the data using any key reference of the certificate obtained from the public apis from gov.uk?
 
Thanks.
Regards.

**Comment by Jaime-CT** [comment]
Hello again,

I would like to know also, if there is a way to obtain the certificate number from the lmk-key. 

Thanks.
Regards.

**Comment by charlesbaird-dsa** [comment]
Hi Jaime - unfortunately we don't have that information - I suggest you try the API documentation at https://epc.opendatacommunities.org/docs/api/domestic#domestic-search in the first instance.
