### ISSUE TITLE
Re: 'Companies House'

### ISSUE THREAD

**Issue by yassine280** [alphagov/api-catalogue#233]
Problem with 'Companies House' (https://www.api.gov.uk/ch/companies-house/)

I am looking for the list of all charges from all the companies available in the UK. 
However there is no command for looping over the charges for each company, which makes this task impossible. 
I need some help!

**Comment by charlesbaird-dsa** [comment]
Hi - you want the Companies House documentation for this: https://developer.company-information.service.gov.uk/
