### ISSUE TITLE
api.gov.uk gives 404 (without www only)

### ISSUE THREAD

**Issue by astreater** [alphagov/api-catalogue#274]
Navigating to https://api.gov.uk is giving me the error "This host is not configured in Transition". the Inspect Console is showing a 404. 

I cleared my local storage, same issue. Can repro on multiple browsers (Chrome, Safari) and also in a private browser session. I'm on a Mac. Same issue on my personal phone (iOS / Safari)

However if I go to www.api.gov.uk it works 

@pggds cannot repro as their browser autodirects to the www version (they are on Windows I believe)

**Comment by jamietanna** [comment]
Discussion continuing on CDDO Slack, with a mix of folks able/unable to repro

**Comment by jamietanna** [comment]
Closing as this no longer seems to be occuring (as of ~1400)
