### ISSUE TITLE
The Apprenticeship Service:Recruitment API

### ISSUE THREAD

**Issue by roysbailey** [alphagov/api-catalogue#276]
**Base URL:**
https://api.apprenticeships.education.gov.uk/managevacancies

**Name:**
Recruitment API

**Description:**
The Recruitment API allows you to create an advert on Find an apprenticeship using your existing systems.  Submitting a new vacancy advert via this API will create the vacancy advert in the live system.  We provide a sandbox version of the API which you can use for testing purposes.  The sandbox is available at: https://api-sandbox.apprenticeships.education.gov.uk/managevacancies.

Note. In order to use the Recruitment API you need to obtain an API key from either an Employer or Training Provider registered on the Apprenticeship Service.  More information is available on the [developer portal](https://developer.apprenticeships.education.gov.uk/).

**Documentation URL:**
https://developer.apprenticeships.education.gov.uk/

**Maintainer:**
Details available on developer portal

**Provider:**
The Apprenticeship Service

**Comment by jamietanna** [comment]
@nahteb should this be closed?
