### ISSUE TITLE
GDS: data.gov.uk

### ISSUE THREAD

**Issue by davidread** [alphagov/api-catalogue#32]
**Base URL:**
https://data.gov.uk/api/action/

**Documentation URL:**
https://guidance.data.gov.uk/get_data/api_documentation/

**Description:**
This API makes accessing the data.gov.uk dataset metadata in a machine-readable way, as JSON. A dataset's metadata includes details such as title, description, usage licence, and a list of 'resources', which describe each data file that makes up the dataset. Each resource contains a format, description and URL (e.g. for download).

**Comment by jonathanglassman** [comment]
Hi @davidread. Thanks for adding this API. The base URL does not appear to work. Can you advise?

**Comment by jonathanglassman** [comment]
> It's just that root URL that is not exposed - maybe something to feed back to the team. The example URLs in the docs do work, such as https://data.gov.uk/api/action/package_list

thank you

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/gds/datagovuk/#data-gov-uk
