### ISSUE TITLE
Add information on the deployment workflow

### ISSUE THREAD

**Issue by Nooshu** [alphagov/api-catalogue#33]
Currently missing details on the correct process used to deploy a new version when required. Things like:

- Uses Github pages so changes need to be merged into the `gh-pages` branch
- What method is used for merging? (`cherry-pick`, `rebase` etc)
- Sample CLI commands on how to merge into `gh-pages`
- Information on the process after the merge (how long it will take, is it automatic etc)

**Comment by odlp** [comment]
Hello. I added some docs around the [current deployment flow](https://github.com/alphagov/api-catalogue/blob/master/docs/deployment.md) - it's the first iteration, feedback most welcome!

**Comment by alex-ju** [comment]
That looks neat @odlp! Super excited to have people working on this as part of a mission!
