### ISSUE TITLE
Scottish Government: statistics.gov.scot API

### ISSUE THREAD

**Issue by ruchaamin** [alphagov/api-catalogue#35]
**Base URL:**
https://statistics.gov.scot/sparql

**Documentation URL:**
https://statistics.gov.scot/sparql?tab=api 
https://guides.statistics.gov.scot/category/37-api

**Description:**
statistics.gov.scot provides public access to the data behind Scotland's official statistics in linked open data format. The SPARQL endpoint allows flexible querying of the datastore using the SPARQL 1.1 language. This API can be used to extract data, automate report-writing, publish data visualisations, or make interactive tools for exploring the data.
The site is managed by the Scottish Government on behalf of all producers of Scottish official statistics including Scottish Government, National Records of Scotland, NHS Information Services Division, Visit Scotland and others.
The API is provided under the Open Government Licence with no requirement for registration.
For queries or comments, please contact statistics.opendata@gov.scot

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/scot/stats/#statistics-gov-scot
