### ISSUE TITLE
Food Standards Agency: Food Hygiene Ratings Scheme

### ISSUE THREAD

**Issue by adamlocker** [alphagov/api-catalogue#38]
**Base URL:**
https://api.ratings.food.gov.uk

**Documentation URL:**
https://api.ratings.food.gov.uk/help

**Description:**
The FHRS API provides free programmatic access to the Food Standards Agency Rating Data for England, Scotland, Wales and Northern Ireland. Developers can leverage FSA data to provide their own services and websites, allowing you to build and develop custom solutions that are consistent with the data being held and displayed by the FSA. As a developer you get access to the same data and the majority of the same functionality that is used to deliver the Food Hygiene Rating Scheme website.

Other than calling the available endpoints, there are no registration requirements for developers before they can start using the Food Standards Agency data. No sign-up process, API keys, or login details are required at this time to use the service.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/fsa/hygiene/#food-hygiene-ratings-scheme-fhrs
