### ISSUE TITLE
Environment Agency: Asset Management API

### ISSUE THREAD

**Issue by DanHaighEA** [alphagov/api-catalogue#40]
**Please fill in the following information:**

**Base URL:**
https://environment.data.gov.uk/asset-management/index.html 

**Documentation URL:**
https://environment.data.gov.uk/asset-management/doc/reference

**Description:**
The Environment Agency maintains records on assets of many types related to environmental activities particularly flood defences, including some assets owned or managed by other bodies. The API provides access to these asset description records along with information on maintenance activities planned for the assets. Only some assets have an associated maintenance schedule.

In the API the maintenance information is split in to three different types. Maintenance activities represent funded and scheduled work. A single activity may involve several maintenance actions on several different assets. We divide the activities into separate tasks, where each task represents a specific maintenance action on a single asset. Finally maintenance plans represent intended maintenance activities for future financial years but which have not necessarily been scheduled or funded at this stage. The API allows all activities, tasks and plans to be listed for a particular asset, set of assets or across all assets.

Please visit the [Defra Data Services Forum](https://support.environment.data.gov.uk/hc/en-gb) to let us know about any issues or to ask questions.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ea/asset/#asset-management
