### ISSUE TITLE
Environment Agency: Bathing Water API

### ISSUE THREAD

**Issue by DanHaighEA** [alphagov/api-catalogue#41]
**Please fill in the following information:**

**Base URL:**
https://environment.data.gov.uk/bwq/index.html

**Documentation URL:**
https://environment.data.gov.uk/bwq/doc/api-reference-v0.6.html

**Description:**
The Environment Agency collects water quality data each year from May to September, to ensure that designated bathing water sites on the coast and inland are safe and clean for swimming and other activities. We make this data reusable and accessible to developers and to members of the public, by publishing it as linked data.

Please visit the [Defra Data Services Forum](https://support.environment.data.gov.uk/hc/en-gb) to let us know about any issues or to ask questions.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ea/bath/#bathing-water
