### ISSUE TITLE
Environment Agency: Catchment Data API

### ISSUE THREAD

**Issue by DanHaighEA** [alphagov/api-catalogue#42]
**Please fill in the following information:**

**Base URL:**
https://environment.data.gov.uk/catchment-planning/ 

**Documentation URL:**
https://environment.data.gov.uk/catchment-planning/ui/reference

**Description:**
The Catchment Data Explorer (CDE) helps you explore and download information about the water environment. It supports and builds upon the data in the river basin management plans. The Catchment Data API complements this by providing selective programmatic access to the data.

Please visit the [Defra Data Services Forum](https://support.environment.data.gov.uk/hc/en-gb) to let us know about any issues or to ask questions.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ea/catch/#catchment-data
