### ISSUE TITLE
Environment Agency: Water Quality API

### ISSUE THREAD

**Issue by DanHaighEA** [alphagov/api-catalogue#43]
**Please fill in the following information:**

**Base URL:**
https://environment.data.gov.uk/water-quality/view/landing 

**Documentation URL:**
https://environment.data.gov.uk/water-quality/view/doc/reference

**Description:**
The Water Quality Archive provides data on water quality measurements carried out by the Environment Agency. Samples are taken from sampling points round the country and then analysed by laboratories to measure aspects of the water quality or the environment at the sampling point. The archive provides data on these measurements and samples dating from 2000 to present day. It contains 58 million measurements on nearly 4 million samples from 58 thousand sampling points.

The archive provides an API to allow selective access to the data, together with the ability to download the data split into either [pre-defined](https://environment.data.gov.uk/water-quality/view/download) or [customizable](https://environment.data.gov.uk/water-quality/view/download/new) subsets. The data is made available in CSV, JSON and RDF formats.

Please visit the [Defra Data Services Forum](https://support.environment.data.gov.uk/hc/en-gb) to let us know about any issues or to ask questions.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ea/quality/#water-quality

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ea/quality/#water-quality
