### ISSUE TITLE
Environment Agency: Hydrology API

### ISSUE THREAD

**Issue by DanHaighEA** [alphagov/api-catalogue#44]
**Please fill in the following information:**

**Base URL:**
https://environment.data.gov.uk/hydrology/landing 

**Documentation URL:**
https://environment.data.gov.uk/hydrology/doc/reference

**Description:**
The Hydrology API provides access to historic water flow information. It complements the near real-time data provided under _/flood-monitoring_ in that it provides access to a long term archive of quality checked and qualified data.

The API and data model for the _/hydrology_ API differs slightly from that under _/flood-monitoring_ due to intrinsic differences (e.g. presence of quality flags on each reading for qualified data), modelling changes (e.g. adding links to [SOSA/SSN](https://www.w3.org/TR/vocab-ssn/) terms) and technology differences.

In addition Environment Agency are moving to using new identifiers for monitoring stations based on GUIDs and the station URIs provided by this API use these new standards. For convenience, the stations shown here provide annotations showing the old stationReference notations (as well as the River Levels on the Internet and WISKI notations) and provide _sameAs_ links to the equivalent _/flood-monitoring_ stations.

Please visit the [Defra Data Services Forum](https://support.environment.data.gov.uk/hc/en-gb) to let us know about any issues or to ask questions.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ea/hydro/#hydrology-api
