### ISSUE TITLE
Environment Agency: Open ePR (electronic Public Register) API

### ISSUE THREAD

**Issue by DanHaighEA** [alphagov/api-catalogue#45]
**Please fill in the following information:**

**Base URL:**
https://environment.data.gov.uk/public-register/view/index

**Documentation URL:**
https://environment.data.gov.uk/public-register/view/api-reference

**Description:**
The Environment Agency licenses industry, business and individuals to carry out certain activities that have the potential to pollute the environment. When we receive an application for such a licence, we make that application and other relevant information available to the public. We do this before we make the decision of whether to issue the licence, or what conditions we will attach to it.

After any permit is issued, further information is also made available on the registers. This can typically include monitoring information, details of any breaches of the terms of the licence, any enforcement actions that we have carried out and any applications to vary the terms of the licence.

The open ePR (electronic Public Register) provides access to this registration and permit information both in the form of searchable web pages and as data which can be accessed by developers via an API.

The APIs cover the following public registers:
- Waste Carriers, Brokers and Dealers
- Waste exemptions
- Scrap Metal Dealers
- Enforcement Actions
- Water Quality Exemptions
- Environmental Permitting Regulations - Radioactive Substances
- Environmental Permitting Regulations - Installations
- Environmental Permitting Regulations - Waste Operations
- Environmental Permitting Regulations - End of Life Vehicles
- Environmental Permitting Regulations - Discharge Consents

These APIs are provided under the [Environment Agency Conditional Licence](https://www.gov.uk/government/publications/environment-agency-conditional-licence/environment-agency-conditional-licence) with no requirement for registration. If you make use of this data please note the conditions carefully.

Please visit the [Defra Data Services Forum](https://support.environment.data.gov.uk/hc/en-gb) to let us know about any issues or to ask questions.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ea/epr/#open-electronic-public-register-epr
