### ISSUE TITLE
Office for National Statistics: Open Geography portal API

### ISSUE THREAD

**Issue by jinman1883** [alphagov/api-catalogue#47]
**Please fill in the following information:**

**Base URL:**
https://ons-inspire.esriuk.com/arcgis/rest/services/

**Documentation URL:**
https://developers.arcgis.com/rest/services-reference/get-started-with-the-services-directory.htm

**Description:**
The Open Geography portal from the Office for National Statistics (ONS) provides free and open access to the definitive source of geographic products, web applications, story maps, services and APIs. All content is available under the Open Government Licence v3.0, except where otherwise stated.

**Comment by TechPunk316** [comment]
This is now live - https://alphagov.github.io/api-catalogue/central/ons/open-geog/#ons-open-geography-portal
