### ISSUE TITLE
Problem with DCS pilot links

### ISSUE THREAD

**Issue by arnau** [alphagov/api-catalogue#53]
Hi,

The DCS pilot has two broken links (base url for production and testing).

https://alphagov.github.io/api-catalogue/central/gds/dcs-pilot/#document-checking-service-pilot-api

**Comment by TechPunk316** [comment]
Hi @pauldougan is this something you can help with?

**Comment by pauldougan** [comment]
sure @TechPunk316 lets catch up next week
