### ISSUE TITLE
Multiple API endpoint

### ISSUE THREAD

**Issue by IeuanWalker** [alphagov/api-catalogue#60]
This is just a query.

We have 10+ API endpoints, and growing.
Would these be individual catalogue entries, or could you group catalogues  by a local government?

**Comment by TechPunk316** [comment]
Hello - we can group them under 'local government' but they would have their individual pages for the description

**Comment by charlesbaird-dsa** [comment]
Hi @IeuanWalker  - the catalogue's been updated so the providing organisation is the top level, each of your endpoints could have its own entry under that. Can we do anything to help get them added?

**Comment by IeuanWalker** [comment]
@charlesbaird-dsa thanks, sounds good.

At the moment our council has a lot of API's that are powering our Mobile app/ Website/ and back office systems.
But all of them are only able to be used by us internal, and don't yet have a way for someone external to utilize them.

So once we have a way for other people to utilize them, we'll look at getting them added here.

Happy for you to close this issue now though :)

**Comment by charlesbaird-dsa** [comment]
Hi @IeuanWalker - fair enough; will close it! Feel free to add the APIs, even if internal at the moment, if you feel like getting a bit of outside interest might help get them developed for external use...
