### ISSUE TITLE
HMRC: GOV.UK Trade Tariff API

### ISSUE THREAD

**Issue by matthewford** [alphagov/api-catalogue#67]
**Base URL:**
`https://www.trade-tariff.service.gov.uk/api/v2`.

**Documentation URL:**
`https://api.trade-tariff.service.gov.uk/`

**Description:**
The GOV.UK Trade Tariff API makes it easy to access Trade Tariff data from https://www.gov.uk/trade-tariff. The data includes commodity codes, import/export controls, customs duty and VAT rates.

It is accessed via HTTPS and returns data in a JSON format. The reference documentation provides a thorough overview of the endpoints and the response format.

**Comment by charlesbaird-dsa** [comment]
Hi Matthew - I'm looking to add this to the catalogue, but need a bit more information about it (for the next iteration of the catalogue we're collecting more metadata) - who's the best person to talk to?

**Comment by matthewford** [comment]
@charlesbaird-dsa I would probably be the best person feel free to get in touch matt@bitzesty.com

**Comment by charlesbaird-dsa** [comment]
This is now live on the API Catalogue - thanks for your help, Matt.
