### ISSUE TITLE
HMRC:Hello World API

### ISSUE THREAD

**Issue by charlesbaird-dsa** [alphagov/api-catalogue#68]
**Please fill in the following information:**

**Base URL:**
https://api.service.hmrc.gov.uk

**Documentation URL:**
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-example-microservice/1.0

**Description:**
This is a test of the catalogue process for CB.

This is an example API that allows software developers to test that their applications can connect with the HMRC API Platform. It also acts as a hands-on tutorial for developers to get started with HMRC APIs.

It includes resources for testing access to the three different access levels:

    Say hello world is an example of an unrestricted endpoint
    Say hello user is an example of a user-restricted endpoint
    Say hello application is an example of an application-restricted endpoint

Further details of the different access levels are given on the Authorisation page.

For more information about how to develop your own client applications, including example clients for this API, see Tutorials.

**Comment by yu600** [comment]
Excuse me, how do I get an OAuth 2.0 access token？ 
![P4E756$TCT7EE%RIWZ6M)12](https://user-images.githubusercontent.com/53322378/90016043-013e5700-dcdc-11ea-89a8-b03ad2c45bb9.png)
 I don't know where scope should be obtained

**Comment by charlesbaird-dsa** [comment]
This is now live on the catalogue.
