### ISSUE TITLE
GOV.UK: Search API

### ISSUE THREAD

**Issue by sihugh** [alphagov/api-catalogue#7]
**Base URL:**
https://www.gov.uk/api/search.json

**Documentation URL:**
https://docs.publishing.service.gov.uk/apis/search/search-api.html

**Description:**
GOV.UK Search API allows you to find content on GOV.UK.  It's the same API that powers https://gov.uk/search/all and the other dynamic content pages on GOV.UK

**Comment by stevenjmesser** [comment]
It'd be great to add third-party uses. I'll chat to DWP.
