### ISSUE TITLE
[ICT/Durham County Council:school names and addresses]

### ISSUE THREAD

**Issue by BriDough** [alphagov/api-catalogue#71]
**Please fill in the following information:**

**Base URL:**
https://www.gov.uk/api/schooldetails.

**Documentation URL:**
The URL for the API documentation. For example `https://content-api.publishing.service.gov.uk/durhamschools`

**Description:**
We would like to link to details held on .gov website that display each school name and address within Durham County as referenced here - https://get-information-schools.service.gov.uk/Establishments/Search?SelectedTab=Establishments&SearchType=ByLocalAuthority&SearchType=ByLocalAuthority&LocalAuthorityToAdd=&d=95&OpenOnly=true&b=1&b=4

Can someone look into provision of an API please that would allow us to access this information rather than exporting to a spreadsheet.

**Comment by keelanfh** [comment]
I don't think this repository is for requests for new APIs, it only documents those that already exist unfortunately.

It might be worth trying to get in touch with the service team on the x-gov Slack.

**Comment by charlesbaird-dsa** [comment]
I believe @BriDough got in touch with people at the DfE re this (feel free to email me at charles.barid@digital.cabinet-office.gov.uk if not!); closing this issue as it's not directly relevant to the API Catalogue.
