### ISSUE TITLE
Fix newline characters in descriptions

### ISSUE THREAD

**Issue by odlp** [alphagov/api-catalogue#89]
Example: https://alphagov.github.io/api-catalogue/EA/Tide_Gauge/#tide-gauge

<img width="1280" alt="newlines-in-description" src="https://user-images.githubusercontent.com/4125410/94259275-1e468680-ff26-11ea-8c0e-92f1ca37625c.png">

We should either strip these, or attempt to convert them into actual newlines / paragraphs.

**Comment by odlp** [comment]
The entry for `Statistics.gov.scot` also appears to have newlines, albeit with a different encoding:

<img width="782" alt="Screenshot 2020-09-28 at 16 46 24" src="https://user-images.githubusercontent.com/4125410/94454744-26aef380-01aa-11eb-9e2b-99d086049ddc.png">

**Comment by edent** [comment]
Another one. `\n` should be parsed and returned as `<br>`

![String literals in a text document.](https://user-images.githubusercontent.com/837136/96116275-21f37a80-0ee0-11eb-9c8c-8fa328d7c6d7.png)

**Comment by edent** [comment]
I think the problem is at:
https://github.com/alphagov/api-catalogue/blob/8de9ac487e6514693a43bdf113533972b54ffb09/source/api_details.html.erb#L26

Rather than using `escape_html` we can use [`sanitize`](https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html)
```
<%= sanitize(@api.description.gsub("\n", "<br />"), :tags => %w(br), :attributes => %w()) %>
```

That replaces newlines with `<br>`, and tells santize to clean everything *except* the `<br>`

**Comment by odlp** [comment]
Thanks @edent for spotting the other cases! I don't think we have `sanitize` available becuase Middleman uses [Padrino's format helpers](http://padrinorb.com/guides/application-helpers/format-helpers/#list-of-format-helpers) rather than ActionView. 

It seems like Padrino's `simple_format` might be a better candidate - it converts single newlines into breaks, and double newlines into paragraphs ([source](https://github.com/padrino/padrino-framework/blob/02feacb6afa9bce20c1fb360df4dfd4057899cfc/padrino-helpers/lib/padrino-helpers/format_helpers.rb#L77-L87)):

```ruby
simple_format("hello\nworld") => "<p>hello<br/>world</p>"
```

I'm going to hold off changing this for now, because we plan to support Markdown in descriptions, which should also resolve the newline characters by introducing paragraphs.
